### ISSUE TITLE
Run instructions?

### ISSUE THREAD

**Issue by Celeo** [adh-partnership/auth#5]
What are the requirements for running this project? Clearly, `.env.example` needs to be copied to `.env` and filled out, and some of the fields are self-explanatory.

Where does the key for the `SSO_JWKS` env var come from?

**Comment by dhawton** [comment]
That's up to you to generate.. it needs to be a JWK KeySet. Unfortunately, running this outside of production environments is not a supported practice due to VATSIM developmental "recommendations".

**Comment by Celeo** [comment]
Okay, so local dev logins can only be done through proxying the frontend to the facility dev environment?
